[bias-values]
Atlantis = {'dgs'=969751.259, 'bgm'=855580.65}  # 2025
Thompson = {'dgs'=969492.789, 'bgm'=855489.8}  # Jan 2026
Revelle = {'dgs'=968888.6465, 'bgm'=855240.81987}
NBP = {'dgs'=968634.2514, 'bgm'=-999}
Ride = {'dgs'=968895.7718, 'bgm'=-999}
Langseth = {'dgs'=969376.125, 'bgm'=854974.4}  # 2025
Sikuliaq = {'dgs'=969538.8152, 'bgm'=-999}   #2025

[nav-talkers]
Atlantis = 'GPGGA'
Thompson = 'INGGA'
NBP = 'GPGGA'
Ride = 'INGGA'
Revelle = 'GPGGA'
Langseth = 'INGGA'
Sikuliaq = 'GPGGA'

[BGM-scale]
Atlantis = 4.994070552
Thompson = 5.003353363
Revelle = 4.99980755
Langseth = 5.0

[dgs-stuff]
calibration_factor = 8388607
